# Configuration de l'application
spring.application.name=gestionprojets

# Base de donnees MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/projectdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=vJWz9bqn35flRzgG8LQEq4cWLEvd1RS2VqB1MAD0GCCSyOmOHtj1emOKnG426VFMN5jXvTPCya5JbtVRJrXj9kjNmOTINalqK0ZK5O2dglNWWy7DLU8G7HgKLOuJll5fGU8AVTtcV2tBpttOm82a4o1eo451rLjlIURhI2gOwcH7AYX98pCnRX4oEB8OVi3AmU709RAKvH9s7FHnVO8QS9k3a4i6Zvv17lStJaQskmcqUluOoeaqzSDZELvfs2l9
app.jwt.expiration=86400000

# Serveur
server.port=8080

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:4200